sudo : required

language : generic

service :
    docker

before_install :
    - docker build -t iwdmlb/docker-react -f Dockerfile.dev .

script :
    - docker run -e CI=true iwdmlb/docker-react npm run test 